# Generated by Django 4.2.4 on 2023-08-27 04:40

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prodavnice', '0002_branch_event_label_repositorium_task_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='ime',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='repositorium',
            name='fork_parent',
        ),
        migrations.AlterField(
            model_name='commit',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 6, 39, 57, 700930)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 6, 39, 57, 699933)),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='startDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 8, 27, 6, 39, 57, 699933)),
        ),
        migrations.AlterField(
            model_name='repositorium',
            name='number_of_forked_project',
            field=models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repositorium',
            name='starred',
            field=models.ManyToManyField(blank=True, related_name='starred', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repositorium',
            name='watched',
            field=models.ManyToManyField(blank=True, related_name='watched', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 6, 39, 57, 698936)),
        ),
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, to='prodavnice.label'),
        ),
    ]
