# Generated by Django 4.2.4 on 2023-08-27 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodavnice', '0003_rename_ime_task_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorium',
            name='number_of_forked_project',
        ),
        migrations.AlterField(
            model_name='commit',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 6, 58, 50, 660738)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 6, 58, 50, 659741)),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='startDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 8, 27, 6, 58, 50, 659741)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 6, 58, 50, 658744)),
        ),
    ]
